# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/explosiveprogrammers/Dev/tl_clothUtils/UI/clothUtilsUI.ui',
# licensing of '/home/explosiveprogrammers/Dev/tl_clothUtils/UI/clothUtilsUI.ui' applies.
#
# Created: Thu Dec 12 12:06:38 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(578, 666)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setContentsMargins(40, 25, 40, 40)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(-1, -1, 6, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.widget_9 = QtWidgets.QWidget(self.widget)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_5.setContentsMargins(12, -1, -1, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.clothObjComboBox = QtWidgets.QComboBox(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clothObjComboBox.sizePolicy().hasHeightForWidth())
        self.clothObjComboBox.setSizePolicy(sizePolicy)
        self.clothObjComboBox.setObjectName("clothObjComboBox")
        self.verticalLayout_5.addWidget(self.clothObjComboBox)
        self.horizontalLayout.addWidget(self.widget_9)
        self.verticalLayout_4.addWidget(self.widget)
        self.widget_10 = QtWidgets.QWidget(self.centralwidget)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.selectClothObj = QtWidgets.QPushButton(self.widget_10)
        self.selectClothObj.setStyleSheet("background-color: rgb(73, 227, 163);\n"
"color: rgb(0, 0, 0);")
        self.selectClothObj.setObjectName("selectClothObj")
        self.horizontalLayout_6.addWidget(self.selectClothObj)
        self.createGraphForClothBtn = QtWidgets.QPushButton(self.widget_10)
        self.createGraphForClothBtn.setStyleSheet("background-color: rgb(73, 227, 163);\n"
"color: rgb(0, 0, 0);")
        self.createGraphForClothBtn.setObjectName("createGraphForClothBtn")
        self.horizontalLayout_6.addWidget(self.createGraphForClothBtn)
        self.verticalLayout_4.addWidget(self.widget_10)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.disableClothObjectCheckBox = QtWidgets.QCheckBox(self.widget_5)
        self.disableClothObjectCheckBox.setObjectName("disableClothObjectCheckBox")
        self.verticalLayout.addWidget(self.disableClothObjectCheckBox)
        self.disableCollisionLayerCheckBox = QtWidgets.QCheckBox(self.widget_5)
        self.disableCollisionLayerCheckBox.setObjectName("disableCollisionLayerCheckBox")
        self.verticalLayout.addWidget(self.disableCollisionLayerCheckBox)
        self.horizontalLayout_2.addWidget(self.widget_5)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.colorisePixelBtn = QtWidgets.QPushButton(self.widget_4)
        self.colorisePixelBtn.setStyleSheet("background-color: rgb(73, 227, 163);\n"
"color: rgb(0, 0, 0);")
        self.colorisePixelBtn.setObjectName("colorisePixelBtn")
        self.verticalLayout_2.addWidget(self.colorisePixelBtn)
        self.coloriseObjectBtn = QtWidgets.QPushButton(self.widget_4)
        self.coloriseObjectBtn.setAutoFillBackground(False)
        self.coloriseObjectBtn.setStyleSheet("background-color: rgb(73, 227, 163);\n"
"color: rgb(0, 0, 0);")
        self.coloriseObjectBtn.setObjectName("coloriseObjectBtn")
        self.verticalLayout_2.addWidget(self.coloriseObjectBtn)
        self.horizontalLayout_3.addWidget(self.widget_4)
        self.verticalLayout_4.addWidget(self.widget_3)
        self.widget_8 = QtWidgets.QWidget(self.centralwidget)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_4.setContentsMargins(-1, -1, 12, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.widget_8)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.colliderObjComboBox = QtWidgets.QComboBox(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colliderObjComboBox.sizePolicy().hasHeightForWidth())
        self.colliderObjComboBox.setSizePolicy(sizePolicy)
        self.colliderObjComboBox.setObjectName("colliderObjComboBox")
        self.horizontalLayout_4.addWidget(self.colliderObjComboBox)
        self.verticalLayout_4.addWidget(self.widget_8)
        self.widget_11 = QtWidgets.QWidget(self.centralwidget)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.selectColliderBtn = QtWidgets.QPushButton(self.widget_11)
        self.selectColliderBtn.setStyleSheet("background-color: rgb(73, 227, 163);\n"
"color: rgb(0, 0, 0);")
        self.selectColliderBtn.setObjectName("selectColliderBtn")
        self.horizontalLayout_7.addWidget(self.selectColliderBtn)
        self.createGraphForColliderBtn = QtWidgets.QPushButton(self.widget_11)
        self.createGraphForColliderBtn.setStyleSheet("background-color: rgb(73, 227, 163);\n"
"color: rgb(0, 0, 0);")
        self.createGraphForColliderBtn.setObjectName("createGraphForColliderBtn")
        self.horizontalLayout_7.addWidget(self.createGraphForColliderBtn)
        self.verticalLayout_4.addWidget(self.widget_11)
        self.widget_6 = QtWidgets.QWidget(self.centralwidget)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.widget_6)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.widget_7 = QtWidgets.QWidget(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.disableColliderObjCheckBox = QtWidgets.QCheckBox(self.widget_7)
        self.disableColliderObjCheckBox.setObjectName("disableColliderObjCheckBox")
        self.verticalLayout_3.addWidget(self.disableColliderObjCheckBox)
        self.coloriseObjectBtn_2 = QtWidgets.QPushButton(self.widget_7)
        self.coloriseObjectBtn_2.setStyleSheet("background-color: rgb(73, 227, 163);\n"
"color: rgb(0, 0, 0);")
        self.coloriseObjectBtn_2.setObjectName("coloriseObjectBtn_2")
        self.verticalLayout_3.addWidget(self.coloriseObjectBtn_2)
        self.horizontalLayout_5.addWidget(self.widget_7)
        self.verticalLayout_4.addWidget(self.widget_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 578, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "clothObject", None, -1))
        self.selectClothObj.setText(QtWidgets.QApplication.translate("MainWindow", "selectCloth", None, -1))
        self.createGraphForClothBtn.setText(QtWidgets.QApplication.translate("MainWindow", "createGraphForCloth", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "disableCloth", None, -1))
        self.disableClothObjectCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "disableClothObject", None, -1))
        self.disableCollisionLayerCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "disableCollisionLayer", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "coloriseCloth", None, -1))
        self.colorisePixelBtn.setText(QtWidgets.QApplication.translate("MainWindow", "colorisePixel", None, -1))
        self.coloriseObjectBtn.setText(QtWidgets.QApplication.translate("MainWindow", "coloriseObject", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "colliderObject", None, -1))
        self.selectColliderBtn.setText(QtWidgets.QApplication.translate("MainWindow", "selectCollider", None, -1))
        self.createGraphForColliderBtn.setText(QtWidgets.QApplication.translate("MainWindow", "createGraphForCollider", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "colliderAction", None, -1))
        self.disableColliderObjCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "disableColllider", None, -1))
        self.coloriseObjectBtn_2.setText(QtWidgets.QApplication.translate("MainWindow", "coloriseCollider", None, -1))

