# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/explosiveprogrammers/Dev/tl_clothUtils/UI/clothUtilsUI.ui',
# licensing of '/home/explosiveprogrammers/Dev/tl_clothUtils/UI/clothUtilsUI.ui' applies.
#
# Created: Mon Dec 16 18:52:58 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(578, 803)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setContentsMargins(40, 25, 40, 40)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.widget_9 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_5.setContentsMargins(18, -1, 6, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.clothObjectsListWidget = QtWidgets.QListWidget(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clothObjectsListWidget.sizePolicy().hasHeightForWidth())
        self.clothObjectsListWidget.setSizePolicy(sizePolicy)
        self.clothObjectsListWidget.setObjectName("clothObjectsListWidget")
        self.verticalLayout_5.addWidget(self.clothObjectsListWidget)
        self.horizontalLayout.addWidget(self.widget_9)
        self.verticalLayout_4.addWidget(self.widget)
        self.widget_8 = QtWidgets.QWidget(self.centralwidget)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_4.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.widget_12 = QtWidgets.QWidget(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_12.sizePolicy().hasHeightForWidth())
        self.widget_12.setSizePolicy(sizePolicy)
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.colliderObjectsListWidget = QtWidgets.QListWidget(self.widget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colliderObjectsListWidget.sizePolicy().hasHeightForWidth())
        self.colliderObjectsListWidget.setSizePolicy(sizePolicy)
        self.colliderObjectsListWidget.setObjectName("colliderObjectsListWidget")
        self.verticalLayout_6.addWidget(self.colliderObjectsListWidget)
        self.horizontalLayout_4.addWidget(self.widget_12)
        self.verticalLayout_4.addWidget(self.widget_8)
        self.widget_10 = QtWidgets.QWidget(self.centralwidget)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.invertSelectionBtn = QtWidgets.QPushButton(self.widget_10)
        self.invertSelectionBtn.setStyleSheet("background-color: rgb(73, 227, 163);\n"
"color: rgb(0, 0, 0);")
        self.invertSelectionBtn.setObjectName("invertSelectionBtn")
        self.verticalLayout_3.addWidget(self.invertSelectionBtn)
        self.coloriseNamesByCollisionLayerBtn = QtWidgets.QPushButton(self.widget_10)
        self.coloriseNamesByCollisionLayerBtn.setStyleSheet("background-color: rgb(73, 227, 163);\n"
"color: rgb(0, 0, 0);")
        self.coloriseNamesByCollisionLayerBtn.setObjectName("coloriseNamesByCollisionLayerBtn")
        self.verticalLayout_3.addWidget(self.coloriseNamesByCollisionLayerBtn)
        self.coloriseNamesBySelectedGroupBtn = QtWidgets.QPushButton(self.widget_10)
        self.coloriseNamesBySelectedGroupBtn.setStyleSheet("background-color: rgb(73, 227, 163);\n"
"color: rgb(0, 0, 0);")
        self.coloriseNamesBySelectedGroupBtn.setObjectName("coloriseNamesBySelectedGroupBtn")
        self.verticalLayout_3.addWidget(self.coloriseNamesBySelectedGroupBtn)
        self.verticalLayout_4.addWidget(self.widget_10)
        self.widget_11 = QtWidgets.QWidget(self.centralwidget)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_5.setContentsMargins(-1, 12, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.widget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.selectGroupByColourComboBox = QtWidgets.QComboBox(self.widget_11)
        self.selectGroupByColourComboBox.setObjectName("selectGroupByColourComboBox")
        self.horizontalLayout_5.addWidget(self.selectGroupByColourComboBox)
        self.verticalLayout_4.addWidget(self.widget_11)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.visibilityCheckBox = QtWidgets.QCheckBox(self.widget_5)
        self.visibilityCheckBox.setObjectName("visibilityCheckBox")
        self.verticalLayout.addWidget(self.visibilityCheckBox)
        self.isolateSelectCheckBox = QtWidgets.QCheckBox(self.widget_5)
        self.isolateSelectCheckBox.setObjectName("isolateSelectCheckBox")
        self.verticalLayout.addWidget(self.isolateSelectCheckBox)
        self.enableCheckBox = QtWidgets.QCheckBox(self.widget_5)
        self.enableCheckBox.setObjectName("enableCheckBox")
        self.verticalLayout.addWidget(self.enableCheckBox)
        self.horizontalLayout_2.addWidget(self.widget_5)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.coloriseByShellBtn = QtWidgets.QPushButton(self.widget_4)
        self.coloriseByShellBtn.setStyleSheet("background-color: rgb(73, 227, 163);\n"
"color: rgb(0, 0, 0);")
        self.coloriseByShellBtn.setObjectName("coloriseByShellBtn")
        self.verticalLayout_2.addWidget(self.coloriseByShellBtn)
        self.coloriseByObjectBtn = QtWidgets.QPushButton(self.widget_4)
        self.coloriseByObjectBtn.setAutoFillBackground(False)
        self.coloriseByObjectBtn.setStyleSheet("background-color: rgb(73, 227, 163);\n"
"color: rgb(0, 0, 0);")
        self.coloriseByObjectBtn.setObjectName("coloriseByObjectBtn")
        self.verticalLayout_2.addWidget(self.coloriseByObjectBtn)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_2.setStyleSheet("background-color: rgb(73, 227, 163);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_3.setStyleSheet("background-color: rgb(73, 227, 163);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.horizontalLayout_3.addWidget(self.widget_4)
        self.verticalLayout_4.addWidget(self.widget_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 578, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "clothObjects", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "colliderObjects", None, -1))
        self.invertSelectionBtn.setText(QtWidgets.QApplication.translate("MainWindow", "invertSelection", None, -1))
        self.coloriseNamesByCollisionLayerBtn.setText(QtWidgets.QApplication.translate("MainWindow", "coloriseNamesByCollisionLayer", None, -1))
        self.coloriseNamesBySelectedGroupBtn.setText(QtWidgets.QApplication.translate("MainWindow", "coloriseNamesBySelectedGroup", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "selectGroupByColor", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "disableCloth", None, -1))
        self.visibilityCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "visibility", None, -1))
        self.isolateSelectCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "isolateSelect", None, -1))
        self.enableCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "enable", None, -1))
        self.coloriseByShellBtn.setText(QtWidgets.QApplication.translate("MainWindow", "coloriseByShell", None, -1))
        self.coloriseByObjectBtn.setText(QtWidgets.QApplication.translate("MainWindow", "coloriseByObject", None, -1))
        self.pushButton_2.setText(QtWidgets.QApplication.translate("MainWindow", "coloriseWholeGroup", None, -1))
        self.pushButton_3.setText(QtWidgets.QApplication.translate("MainWindow", "coloriseGreyLambert", None, -1))

